// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvEVsT1d0vc-TxB5kRu-Tfm8UBybEDbM',
    appId: '1:549192150308:web:2d245b4d3e0003dce797b1',
    messagingSenderId: '549192150308',
    projectId: 'lostfoundvision-bb117',
    authDomain: 'lostfoundvision-bb117.firebaseapp.com',
    storageBucket: 'lostfoundvision-bb117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTl99YfDFnFvImxZoTylD-G5265aKvg0',
    appId: '1:549192150308:android:791dc34a515ca6eae797b1',
    messagingSenderId: '549192150308',
    projectId: 'lostfoundvision-bb117',
    storageBucket: 'lostfoundvision-bb117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW_C2ky5sJRaF7ShbIzh-5hjdZiJU7QA',
    appId: '1:549192150308:ios:6e1dc069061bebbae797b1',
    messagingSenderId: '549192150308',
    projectId: 'lostfoundvision-bb117',
    storageBucket: 'lostfoundvision-bb117.appspot.com',
    iosBundleId: 'com.example.fortest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtW_C2ky5sJRaF7ShbIzh-5hjdZiJU7QA',
    appId: '1:549192150308:ios:d121e3d2e8306f29e797b1',
    messagingSenderId: '549192150308',
    projectId: 'lostfoundvision-bb117',
    storageBucket: 'lostfoundvision-bb117.appspot.com',
    iosBundleId: 'com.example.fortest.RunnerTests',
  );
}
